# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 111, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 10, 671, 561))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.widget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuInstrument = QtWidgets.QMenu(self.menubar)
        self.menuInstrument.setObjectName("menuInstrument")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuEffect = QtWidgets.QMenu(self.menubar)
        self.menuEffect.setObjectName("menuEffect")
        MainWindow.setMenuBar(self.menubar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionBrush = QtWidgets.QAction(MainWindow)
        self.actionBrush.setObjectName("actionBrush")
        self.actionLine = QtWidgets.QAction(MainWindow)
        self.actionLine.setObjectName("actionLine")
        self.actionCircle = QtWidgets.QAction(MainWindow)
        self.actionCircle.setObjectName("actionCircle")
        self.actionSquare = QtWidgets.QAction(MainWindow)
        self.actionSquare.setObjectName("actionSquare")
        self.actionhj = QtWidgets.QAction(MainWindow)
        self.actionhj.setObjectName("actionhj")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionBlack = QtWidgets.QAction(MainWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionWhite = QtWidgets.QAction(MainWindow)
        self.actionWhite.setObjectName("actionWhite")
        self.actionRed = QtWidgets.QAction(MainWindow)
        self.actionRed.setObjectName("actionRed")
        self.actionBlue = QtWidgets.QAction(MainWindow)
        self.actionBlue.setObjectName("actionBlue")
        self.actionGreen = QtWidgets.QAction(MainWindow)
        self.actionGreen.setObjectName("actionGreen")
        self.actionCustom = QtWidgets.QAction(MainWindow)
        self.actionCustom.setObjectName("actionCustom")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionText = QtWidgets.QAction(MainWindow)
        self.actionText.setObjectName("actionText")
        self.actionEraser = QtWidgets.QAction(MainWindow)
        self.actionEraser.setObjectName("actionEraser")
        self.actionSpray = QtWidgets.QAction(MainWindow)
        self.actionSpray.setObjectName("actionSpray")
        self.actionNegative = QtWidgets.QAction(MainWindow)
        self.actionNegative.setObjectName("actionNegative")
        self.actionBlackWhiteFilter = QtWidgets.QAction(MainWindow)
        self.actionBlackWhiteFilter.setObjectName("actionBlackWhiteFilter")
        self.actionNoise = QtWidgets.QAction(MainWindow)
        self.actionNoise.setObjectName("actionNoise")
        self.actionSepia = QtWidgets.QAction(MainWindow)
        self.actionSepia.setObjectName("actionSepia")
        self.actionBlack_White = QtWidgets.QAction(MainWindow)
        self.actionBlack_White.setObjectName("actionBlack_White")
        self.actionProfile = QtWidgets.QAction(MainWindow)
        self.actionProfile.setObjectName("actionProfile")
        self.menuInfo.addAction(self.actionProfile)
        self.menuInfo.addSeparator()
        self.menuInfo.addAction(self.actionInfo)
        self.menuInfo.addSeparator()
        self.menuInfo.addAction(self.actionSave)
        self.menuInfo.addAction(self.actionLoad)
        self.menuInstrument.addSeparator()
        self.menuInstrument.addAction(self.actionBrush)
        self.menuInstrument.addAction(self.actionLine)
        self.menuInstrument.addAction(self.actionCircle)
        self.menuInstrument.addAction(self.actionSquare)
        self.menuInstrument.addAction(self.actionText)
        self.menuInstrument.addAction(self.actionSpray)
        self.menuInstrument.addSeparator()
        self.menuInstrument.addAction(self.actionEraser)
        self.menuInstrument.addSeparator()
        self.menuInstrument.addAction(self.actionCustom)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEffect.addAction(self.actionNegative)
        self.menuEffect.addAction(self.actionBlackWhiteFilter)
        self.menuEffect.addAction(self.actionNoise)
        self.menuEffect.addAction(self.actionSepia)
        self.menuEffect.addAction(self.actionBlack_White)
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuInstrument.menuAction())
        self.menubar.addAction(self.menuEffect.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuInfo.setTitle(_translate("MainWindow", "File"))
        self.menuInstrument.setTitle(_translate("MainWindow", "Instrument"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuEffect.setTitle(_translate("MainWindow", "Effect"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionBrush.setText(_translate("MainWindow", "BrushPoint"))
        self.actionBrush.setShortcut(_translate("MainWindow", "Ctrl+0"))
        self.actionLine.setText(_translate("MainWindow", "Line"))
        self.actionLine.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionCircle.setText(_translate("MainWindow", "Circle"))
        self.actionCircle.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.actionSquare.setText(_translate("MainWindow", "Square"))
        self.actionSquare.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.actionhj.setText(_translate("MainWindow", "hj"))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionSave_2.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionBlack.setText(_translate("MainWindow", "Black"))
        self.actionBlack.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionWhite.setText(_translate("MainWindow", "White"))
        self.actionWhite.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionRed.setText(_translate("MainWindow", "Red"))
        self.actionBlue.setText(_translate("MainWindow", "Blue"))
        self.actionGreen.setText(_translate("MainWindow", "Green"))
        self.actionCustom.setText(_translate("MainWindow", "Change Color"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionText.setText(_translate("MainWindow", "Text"))
        self.actionText.setShortcut(_translate("MainWindow", "Ctrl+4"))
        self.actionEraser.setText(_translate("MainWindow", "Eraser"))
        self.actionEraser.setShortcut(_translate("MainWindow", "Ctrl+6"))
        self.actionSpray.setText(_translate("MainWindow", "Spray"))
        self.actionSpray.setShortcut(_translate("MainWindow", "Ctrl+5"))
        self.actionNegative.setText(_translate("MainWindow", "Negative"))
        self.actionBlackWhiteFilter.setText(_translate("MainWindow", "Old"))
        self.actionNoise.setText(_translate("MainWindow", "Noise"))
        self.actionSepia.setText(_translate("MainWindow", "Sepia"))
        self.actionBlack_White.setText(_translate("MainWindow", "Black White"))
        self.actionProfile.setText(_translate("MainWindow", "Profile"))
